swarmcity/sc-boardwalk

- index.html
- polymer.json
- src/sc-appuser/demo/index.html
- src/sc-appuser/sc-appuser.html
- src/sc-dealchat/sc-dealchat.html
- src/sc-dealfeedback/sc-dealfeedback.html
- src/sc-dealfortwo/sc-dealfortwo-provider.html
- src/sc-dealfortwo/sc-dealfortwo-seeker.html
- src/sc-dealitem/sc-dealitem.html
- src/sc-hashtag/sc-hashtag.html
- src/sc-home/sc-home.html
- src/sc-itemdetail/sc-itemdetail.html
- src/sc-itemreplier/sc-itemreplier.html
- src/sc-itemreply/sc-itemreply.html
- src/sc-listeners/sc-listeners.html
- src/sc-newitem/sc-newitem.html
- src/sc-notifications/demo/index.html
- src/sc-notifications/sc-notificationbadge.html
- src/sc-notifications/sc-notifications.html
- src/sc-profile/sc-profile.html
- src/sc-redux/sc-redux.html
- src/sc-vault/sc-vault.html
- src/sc-walletview/sc-walletview.html
Polymer build now builds the project, there is still a warning about 
```src/sc-ipfs/js-ipfs-api.js(10748,28) warning [unknown-superclass] - Unable to resolve superclass TransformStream```
> #198 polymer build fails

- src/sc-profile/sc-profile.html
> Issue #145

- src/sc-vault/sc-vault.html
ignore commit message, this obviously doesn't apply to password fields. brainfart.
> issue #143 submit on enter, pk and ipfshash

- src/sc-password/sc-password.html
took the liberty to change this a little.
> Issue #147 with modifications for private key

- src/sc-swtconversion/sc-swtconversion.html
Fixes https://github.com/swarmcity/sc-boardwalk/issues/246, https://github.com/swarmcity/sc-boardwalk/issues/255
> Swt conver fixes

- src/sc-vault/sc-vault.html
@faffydee sorry I took so long to throw throw this up :sweat_smile:
> avatar and username on login screen (Issue #185)

- src/sc-swtconversion/sc-swtconversion.html
Fix https://github.com/swarmcity/sc-boardwalk/issues/255
> incresed gas to prevent out of gas

- issue_template.md
Updated issue template to ask for more information specifially OS and browser version. 
This should make things easier for us and allow us to prioritize our target environment.
> added more info to issue template

- src/sc-filter/sc-filter.html
- src/sc-tokensend/sc-tokensend.html
solving geofencing usability #236
> issues #236 #213 #228

- src/sc-config/sc-config.html
- src/sc-filter/sc-filter.html
- src/sc-hashtag/sc-hashtag.html
Solving #254 And after @sponnet created range persistence in localstorage. @kingflurkel requested the ability to define a default range/hashtag (and a default).
Range selector now defaults to the hashtag default unless localstorage has a different value.
> HashtagRange

- src/sc-config/sc-config.html
- src/sc-filter/sc-filter.html
- src/sc-hashtag/sc-hashtag.html
issue #236 the triangle now toggles the slider
> Triangle collapse

- src/sc-home/sc-home.html
fix https://github.com/swarmcity/sc-boardwalk/issues/284
> made hash symbol clickable

- src/sc-newitem/sc-newitem.html
https://github.com/swarmcity/sc-boardwalk/issues/291
> changed hashtag fee to two words

- src/sc-filter/sc-filter.html
> added range 4.

- src/sc-dealchat/sc-dealchat.html
- src/sc-dealfeedback/sc-dealfeedback.html
- src/sc-dealfortwo/sc-dealfortwo-provider.html
- src/sc-dealfortwo/sc-dealfortwo-seeker.html
- src/sc-enter/sc-enter.html
- src/sc-filter/sc-filter.html
- src/sc-hashtagitem/sc-hashtagitem.html
- src/sc-itemdetail/sc-itemdetail.html
- src/sc-itemreplier/sc-itemreplier.html
- src/sc-newitem/sc-newitem.html
- src/sc-profile/sc-hashtagactivity.html
didn't appear to break anything: fixes for #295
> fixes for 295

- src/sc-filter/sc-filter.html
suggestions for issue #286 
any better ideas?
> some suggestions for distance descriptions

- src/sc-newitem/sc-newitem.html
added min = 0.1 and steps of 0.1 SWT to spinner
> #317 SWT numeric spinner input shouldn't show negative value 

- src/sc-boardwalk-app/sc-boardwalk-app.html
- src/sc-config/sc-config.html
- src/sc-ethbalanceformatter/sc-ethbalanceformatter.html
- src/sc-profile/sc-profile.html
- src/sc-tokenbalanceformatter/sc-tokenbalanceformatter.html
#326 
isolated token unit list (away from sc-config)
duplicated & modified tokenbalanceformatter for ethbalanceformatter
added ethbalanceformatter to sc-profile
> Ether balance formatting

- src/sc-profile/sc-profile.html
> Eth balance rounding to 3 decimals

- src/sc-hashtagitem/sc-hashtagitem.html
> sort replies by time ascending

- src/sc-newitem/sc-newitem.html
- src/sc-tokensend/sc-tokensend.html
> Only allow numbers and "." in sc-newitem swt input

- src/sc-ethbalanceformatter/sc-ethbalanceformatter.html
- src/sc-profile/sc-profile.html
- src/sc-tokenbalanceformatter/sc-tokenbalanceformatter.html
added nbsp for whitespace and strip-whitespace tag in template element
> #311 missing space

- src/sc-enter/sc-enter.html
> correct link
